{% set name = "glew" %}
{% set version = "2.2.0" %}
{% set dev_url = "https://github.com/nigels-com/glew" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: {{ dev_url }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: d4fc82893cfb00109578d0a1a2337fb8ca335b3ceccf97b97e5cc7f08e4353e1
  patches:  # [win]
    # turn on experimental to allow GL 3.x+ (required on modern Windows)
    - glew_win.patch  # [win]

build:
  number: 2
  # Missing CDT packages on s390x and ppc64le
  skip: true  # [s390x or ppc64le]
  run_exports:
    - {{ pin_subpackage('glew', max_pin='x.x') }}
  missing_dso_whitelist:
    - "**/libc.so.*"
    - "**/libGLEW.*"

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
    - pkg-config
    - m2-patch  # [win]
    # TODO: map CDT mesa-libegl-devel to new X11 package
    # - { cdt('mesa-libegl-devel') }
    # TODO: map CDT alsa-lib-devel to new X11 package
    # - { cdt('alsa-lib-devel') }
    # TODO: map CDT gtk2-devel to new X11 package
    # - { cdt('gtk2-devel') }
    # TODO: map CDT gtkmm24-devel to new X11 package
    # - { cdt('gtkmm24-devel') }
    # TODO: map CDT libdrm-devel to new X11 package
    # - { cdt('libdrm-devel') }
    # TODO: map CDT pciutils-devel to new X11 package
    # - { cdt('pciutils-devel') }
    # TODO: map CDT libselinux-devel to new X11 package
    # - { cdt('libselinux-devel') }
    # TODO: map CDT libxrandr to new X11 package
    # - { cdt('libxrandr') }
    # TODO: map CDT alsa-lib to new X11 package
    # - { cdt('alsa-lib') }
  host:
    - libglu  # [linux]
    - xorg-xproto
    - xorg-libx11
    - xorg-libxext
    - xorg-libxrender
    - libgl-devel
    - mesa-dri-drivers
    - xorg-libxau
    - xorg-libxcomposite
    - xorg-libxcursor
    - xorg-libxi
    - xorg-libxrandr
    - xorg-libxscrnsaver
    - xorg-libxtst
    - xorg-libxdamage
    - xorg-libxdamage
    - xorg-libxfixes
    - xorg-libxfixes
    - xorg-libxxf86vm
    - libxcb
    - xorg-libxdamage
    - xorg-libxext
    - xorg-libxfixes
    - xorg-libxxf86vm
    - libgl-devel
    - mesa-dri-drivers
  run:
    - libglu  # [linux]

# Tests require visual context not present on CIs
test:
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - python
    - make  # [unix]
    # TODO: map CDT libselinux to new X11 package
    # - { cdt('libselinux') }
    # TODO: map CDT libxau to new X11 package
    # - { cdt('libxau') }
  commands:
    - test -f $PREFIX/include/GL/glew.h  # [unix]
    - if not exist %LIBRARY_INC%\GL\glew.h exit 1  # [win]
    - ./run_test.sh  # [unix]
    - run_test.bat  # [win]

about:
  home: https://glew.sourceforge.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The OpenGL Extension Wrangler Library
  description: |
    The OpenGL Extension Wrangler Library (GLEW) is a cross-platform open-source C/C++
    extension loading library. GLEW provides efficient run-time mechanisms for determining
    which OpenGL extensions are supported on the target platform. OpenGL core and extension
    functionality is exposed in a single header file.
  doc_url: https://glew.sourceforge.net/basic.html
  dev_url: {{ dev_url }}

extra:
  skip-lints:
    - host_section_needs_exact_pinnings  # no need to pin here for now
    - has_run_test_and_commands  # manually invoked ... so ok
  recipe-maintainers:
    - dschreij
    - edisongustavo