{% set name = "glew" %}
{% set version = "2.2.0" %}
{% set dev_url = "https://github.com/nigels-com/glew" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tgz
  url: {{ dev_url }}/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tgz
  sha256: d4fc82893cfb00109578d0a1a2337fb8ca335b3ceccf97b97e5cc7f08e4353e1
  patches:  # [win]
    # turn on experimental to allow GL 3.x+ (required on modern Windows)
    - glew_win.patch  # [win]

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('glew', max_pin='x.x') }}
  missing_dso_whitelist:
    - "**/libc.so.*"

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - make      # [unix]
    - ninja     # [win]
    - pkg-config
    - m2-patch  # [win]
    - perl      # [unix]
    - sed       # [unix]
  host:
    - libglu                     # [linux]
    - libgl-devel                # [linux]
    - libegl-devel               # [linux] 
    - xorg-libx11                # [linux]
    - xorg-libxmu                # [linux]
    - xorg-libxi                 # [linux]

# Tests require visual context not present on CIs
test:
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - python
    - make                       # [unix]
    - libgl-devel                # [linux]
    - libegl-devel               # [linux]
    - libglu                     # [linux]
    - libxcb                     # [linux]
    - mesalib                    # [linux]
    - xorg-libx11                # [linux]
    - xorg-libxau                # [linux]
    - xorg-libxdamage            # [linux]
    - xorg-libxext               # [linux]
    - xorg-libxfixes             # [linux]
    - xorg-libxxf86vm            # [linux]
  commands:
    - test -f $PREFIX/include/GL/glew.h  # [unix]
    - if not exist %LIBRARY_INC%\GL\glew.h exit 1  # [win]
    
    # Test GLEW utilities as documented at https://glew.sourceforge.net/basic.html
    - test -f $PREFIX/bin/glewinfo  # [unix]
    - test -f $PREFIX/bin/visualinfo  # [unix]
    - if not exist %LIBRARY_BIN%\glewinfo.exe echo "glewinfo utility not found (may be expected)"  # [win]
    - if not exist %LIBRARY_BIN%\visualinfo.exe echo "visualinfo utility not found (may be expected)"  # [win]

about:
  home: https://glew.sourceforge.net/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: The OpenGL Extension Wrangler Library
  description: |
    The OpenGL Extension Wrangler Library (GLEW) is a cross-platform open-source C/C++
    extension loading library. GLEW provides efficient run-time mechanisms for determining
    which OpenGL extensions are supported on the target platform. OpenGL core and extension
    functionality is exposed in a single header file.
  doc_url: https://glew.sourceforge.net/basic.html
  dev_url: {{ dev_url }}

extra:
  skip-lints:
    - host_section_needs_exact_pinnings  # no need to pin here for now
    - has_run_test_and_commands  # manually invoked ... so ok
  recipe-maintainers:
    - dschreij
    - edisongustavo
