travis:
  secure:
    BINSTAR_TOKEN: fvrbuZ14Ln98YbOB2UL/gcgACEOiCKIdukvJ5+Oiz9DT47pvbHfgPww8OsoZtiYf9/iWMll4MKhZ9b1aU5MzPv6K6nESd7FpDSmRhSGdp48Zl6Z3ympRvRXBcfamU8Lp+qGZgr2KcoGxeRb4ycD0gGN2bj2gFYr7dbcb9o3EghW77a6iQszEB0Cv7IAUPyUuK0Otmiot4u6tYuEo6SJ4kEjCevJGue7EUaNT9IdFCocqsL4YkPoKVL46Pbwr8GJVnJ3Xh+6rqDpDSZB0K5R35Wgd/su5tC6trm5f3uMOomHJjYVZli026HT8pmk3Jq4LVwOIGUxwc+jgSpUO2G2KIOcmSh5dzJDj1trByWEx7iXPKjjFjZelfatSyrC/kigHrz7OCaXkVNqlpFPiSGTpfi2GVzBeEceTuP5KUvJF1xjS3dGSboK0KIjqBgdpkhkREJ7yOo4QW2WasSSUQeDFOymG2QaGzpqUNNTCHs6WDm2DjxMJOOYo8f9DhVWK0p+0YuDrJk+vfSxeoZ+b2XVaispxDf5cNkLs/FpRcz2ySPWRbfhGMpV6aFx+5wKPPGJRo+rxRiiP3O0BydITaaPFGW0ceKlpzPcFEA1A24un9qnICfEq0Gu81HE/zq7LttRADW1lhCLfDZ/gXt0LowWk3fLUlTkSAQWRCs/J/IG4xTg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
