travis:
  secure:
    BINSTAR_TOKEN: Ue9KVUlcBY+xjH2pnXWwfJy/w7Q5eRXr2Ub8p/gANkFCRJ8FldEnZAOCAgZn6OeIafBtC0ajRht236E3RghgG52M7tOdFJr8DYY+IIVWI3WmIRje6nrSAVnCJ5B1nr6jMVaJkCQPYES5zNH1Quj57jEqr8t1UFCT0UFw7MO3hzm1NJWL0jDf0u5Ieqx1w6r5qZYI2cTY4kQn68WmPE9I/4gcxfFTnTI8WyxrIriB2iTGfYRzOcP4EbUvOQ0fWg/zpTnBb2lT2AY78xl/3HAA6uqb24pXSfPl+rZ4++7D8NpPHD3s9fGspJW9IaOsVsK+1vTKZYLBUkOcz0/uk/W85UFKqMNy7v9WwjYReLGSiYQCKyNRzQ5TNSB6pjT05DHbl8IyEpn/bIsarSaFG5EsdMcJZm5RpxX3bMcQkXlzZ/F5LT973KAhu/PZ5B4SoxF4e8ndBsKSE3DAkARILmewP0HxWA7Yp8m4bC7xlW3mH+Pc3zYzo4MURshzjWTEC6+sohEIdgHkbDX8fwfv5dR1socB2z3hOQl6CO+Uy7Ud52UNsZwZOn41pdJfnSFu9VlyA0wNWx9GjqfoGwsDl72dL4vlepPZ1oO7/myeh3qX32tWJ5q0S9JTa1yU6n28IMJH5Bz6I/JO3ycZHZuDCiIJ2mfcfjhKjpjit4YY7t9Xf88=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
